opentdf/web-sdk

lib/src/index.ts

- We are looking for 3 bytes, not 3 nibbles

🐛 Fix incorrect dataset i.v. guard

---

cli/README.md
cli/package-lock.json
cli/package.json
cli/src/cli.ts
lib/package-lock.json
lib/src/index.ts
sample-web-app/package-lock.json
sample-web-app/package.json

- Sets cli and sample app version numbers to 0.1.1
- updates package-locks to reflect correct version numbers
- removes some no-longer needed polyfill stuff from cli, since we now have nodejs support in lib
- don't warn about empty policies if dissems OR attributes are empty, but if dissems AND attributes are empty
- Update the cli readme for the latest quickstart URIs

🐛 Fix version numbers, other little things

---

lib/src/index.ts
lib/src/nanotdf-crypto/index.ts
lib/src/nanotdf-crypto/keyAgreement.ts
lib/src/nanotdf/Client.ts
lib/src/version.ts
lib/test/nano-roundtrip.test.ts
lib/tsconfig.json

- Adds a round-trip test for nanotdf encrypt/decrypt
- like the 'roundtrip' tests in tdf3-js, this mocks out the entirety of the key rewrap mechanism, which is arguably the harder bit
- removes the unused unwrappedKey field. Really, we need to do an audit to make this more functional overall and less state-preserving
- Adds back source maps for better error reports. 
- We should build on top of this somehow to add more coverage of unusual situations

✅ round trip test, less rewrap

---

lib/facade/FileClient.ts
lib/package.json
lib/src/auth/virtru-oidc.ts
lib/src/tdf/AttributeObject.ts
lib/tdf3/src/ciphers/aes-gcm-cipher.ts
lib/tdf3/src/ciphers/symmetric-cipher-base.ts
lib/tdf3/src/client/validation/validations.ts
lib/tdf3/src/crypto/browser-js-crypto-service.ts
lib/tdf3/src/crypto/node-crypto-service.ts
lib/tdf3/src/models/attribute-set.ts
lib/tdf3/src/models/encryption-information.ts
lib/tdf3/src/models/index.ts
lib/tdf3/src/models/key-access.ts
lib/tdf3/src/models/manifest.ts
lib/tdf3/src/models/payload.ts
lib/tdf3/src/models/policy.ts
lib/tdf3/src/templates/default.html.ts
lib/tdf3/src/utils/chunkers.ts
lib/tdf3/src/utils/zip-reader.ts
lib/tdf3/test/perf.spec.js
lib/tdf3/test/unit/attribute-set.spec.ts
lib/tdf3/test/unit/chunkers.spec.ts
lib/tdf3/test/unit/zip.spec.ts
lib/tsconfig.json

- More return types
- fewer ts-ignores
- some more types!

🏷 typescript enhancements

---

cli/package-lock.json
lib/lic-checker-config.yaml
lib/package-lock.json
lib/package.json
sample-web-app/package-lock.json

this was used to decide when to use sjcl instead of safari but we no longer support older (2017 & earlier) safaris

➖ Removes unused dep on ua-parser

---

lib/tdf3/src/client/DecoratedReadableStream.ts
lib/tdf3/src/client/builders.ts

- We upgraded to AWS JS sdk 3 some time ago and these values are unused or renamed.
- signature is now fixed to one version
- I'm not sure about key - but it seems to be handled entirely within Upload.ts

🔥 Removed aws-sdk v2 params

---

cli/package-lock.json
lib/tdf3/src/crypto/index.ts
lib/tdf3/test/setup.js
sample-web-app/package-lock.json

When loading the generated cjs in node contexts, the relevant code generates a value error on dereference. Checking for undefined explicitly should prevent this behavior.

🐛 Fix a ReferenceError in node

---

.github/workflows/build.yaml
.github/workflows/format.yaml
.github/workflows/roundtrip/encrypt-decrypt.sh
.github/workflows/roundtrip/wait-and-test.sh
lib/tsconfig.json

- Move format out to its own workflow since it is all by itself anyway and kinda different
- improve error messaging
- Don't re-install npm in the retry loop; only do that once

🔨 CI workflow improvements

---

.github/workflows/build.yaml
.github/workflows/gh-semver.sh
.github/workflows/publish-to.sh
scripts/check-version-is.sh

- Annotate the workflow with the generated semver and tag
- Set access level to public, fixing issue with 'first publish' failing to npm (probably)
- Since npm publish depends on GHPR publish, do that first always, and share the knowledge between them

🚀 Publish fixes & polish

---

lib/tdf3/src/utils/zip-writer.ts
lib/tdf3/test/binary-stress.spec.ts

This avoids failures on loading in a non-Buffer providing environment

🐛 Remove module-level references to Buffer

---

cli/package-lock.json
lib/prepareNodeESM.js
lib/tdf3/src/FileClient.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/client/tdf-stream.ts
lib/tdf3/src/tdf.ts
lib/tdf3/src/utils/chunkers.ts
lib/tdf3/src/utils/index.ts
lib/tdf3/test/client.spec.js
web-app/package-lock.json

- Fix types for tdf-stream aliased module
- Update types around tdfstream generally to be more sensible without needing to load the alias module

🐛 Fix broken conditional exports

---

lib/tdf3/src/FileClient.ts
lib/tdf3/src/client/builders.ts
lib/tdf3/test/unit/FileClient.spec.ts

Previously, the source and params options were exclusive. With this fix, they are properly merged (again)

🐛 Fix mixing FileClient 'source' and params

---

.github/workflows/build.yaml
scripts/check-version-is.sh

- Remove use of `::set-output` in favor of new `GITHUB_OUTPUT` environment file
- Update to latest kube-tools action which also has this problem

🚨 Fixes a few github action warnings

---

.github/workflows/format.yaml

The auto-commit workflow doesn't work on untrusted forks, and probably isn't worth the trouble to fix. Let's see how this works for contributors

🔨 Require `make format` on fork PRs

---

lib/package.json

- Maybe we should rename the web-esm to just tsconfig, as that is the 'reference' we are shooting for with our ESM/browser-first library philosophy

🐛 Fix typedoc line

---

.github/workflows/publish-to.sh
scripts/bump-version.sh
scripts/check-version-is.sh

- sed -I is not in the posix standard, and has different properties, so either don't use it or work around it
- there was an error in the grep logic so I made it more straightforward and used the long versions of the arguments for clarity. IDK if they are all standard but the arguments were in the man pages on both macOS and ubuntu (latest)

🐛 Fix sed and grep errors and x-plat problems

---

lib/tdf3/src/client/builders.ts

- These need to be encoded as buffers

🐛 Fix string sources

---

lib/tdf3/src/errors.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/errors.spec.ts

still keep stack trace and messages, but removes 'data' and 'config' information from axios errors, most notably

🧽 Remove potential PII from 'cause' objects

---

cli/package-lock.json
lib/tdf3/src/client/BrowserTdfSteam.ts
lib/tdf3/src/client/DecoratedReadableStream.ts
lib/tdf3/src/client/NodeTdfStream.ts
lib/tests/mocha/perf.spec.js
web-app/package-lock.json
web-app/package.json
web-app/public/sw.js
web-app/src/App.tsx
web-app/src/main.tsx
web-app/tests/README.md
web-app/tests/package-lock.json
web-app/tests/package.json
web-app/tests/playwright.config.ts
web-app/tests/static-server.js
web-app/tests/tests/roundtrip.spec.ts
web-app/tsconfig.json

Adds a few alternatives and buttons to see if where the different bugs might exist. notably:
1. Adds a 'how to save' selector, to allow dumping the stream, for selecting between Streamsaver (default download), fsapi (called Save As... although only Chrome actually opens the file save dialog), and 'none' (dump to a null writer). 
2. Adds a 'demo scan' button, which doesn't use our library at all but just does some text processing from a Jake Archibald demo
3. Adds a rate limited progress logger to the console
4. Adds 'cancel' button to abort longer streams

⚗️ Adds more test scenarios to web-app

---

.github/workflows/build.yaml

Use the same logic found in `publish_to` to get the correct name for the version identifier

🐛 Fixes version sent on xtest dispatch

---

lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/tdf.spec.ts

We use this behavior in protect-and-track, as part of 'download tdf' hack

🐛 Lets unwrapHtml take a string

---

lib/tdf3/index.ts
lib/tdf3/src/crypto/declarations.ts
lib/tdf3/src/crypto/index.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/crypto-di.spec.ts
web-app/package-lock.json

- updates export to include Chunker, useful in directly calling decrypt with no builder
- lets `cryptoToPemPair` take an unknown argument. Sometimes generics [just don't work](https://stackoverflow.com/a/105812)

✨Type fixes

---

lib/tdf3/src/models/encryption-information.ts

To make the client-web more conformant to the specification, remove `segmentHash`
See https://github.com/opentdf/spec/blob/main/schema/tdf/manifest-json.md#encryptioninformationintegrityinformation
```
"integrityInformation": {
"rootSignature": {
"alg": "HS256",
"sig": "M2E2MTI5YmMxMWU0ODIzZDA4YTdkNTY2MzdlNDM4OGRlZDE2MTFhZjU1YTY1YzBhYWNlMWVjYjlmODUzNmNiZQ=="
},
"segmentHashAlg": "GMAC",
"segments": [<Segment Object>],
"segmentSizeDefault": 1000000,
"encryptedSegmentSizeDefault": 1000028
}
```

Remove segmentHash from integrityInformation

---

.github/workflows/publish-to.sh

- This hopefully fill fix the issue with betas being tagged latest

🐛 Moves misplaced `--tag` flag

---

Makefile
lib/package-lock.json
lib/package.json
lib/src/nanotdf/Client.ts
lib/src/utils.ts
lib/src/version.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/errors.ts
lib/tdf3/src/tdf.ts
lib/tdf3/src/version.ts
lib/tests/mocha/unit/tdf.spec.ts
lib/tests/web/utils.test.ts
web-app/package-lock.json
web-app/package.json

Why? TDF files should be considered user generated content, and any data from them should be suspect. In this case, we don't want to send random upsert / rewrap requests to unknown/unsafe URIs.
This throws an UnsafeUrlError in this case, which has a `.url` parameter which will allow applications to prompt the user to see if the URL is 'safe'.

🚨 Require allowlisting KASes on decrypt and upsert

---

lib/package.json
lib/tdf3/src/models/attribute-set.ts
lib/tests/mocha/encrypt-decrypt.spec.ts
lib/tests/mocha/unit/attribute-set.spec.ts
lib/tests/mocha/unit/tdf.spec.ts

- depending on the bundler, it seems to be either default or not???
- Notably, in protect-and-track, this causes it to fail with `Uncaught TypeError: n.default is not a constructor`
- Found an issue where a mock TDF.create was escaping its test harness and breaking other tests
- This would have shown up earlier, but we've been ignoring mocha's return value in CI 😬

🐛 Fix broken AJV constructor

---

lib/package.json
lib/tdf3/src/utils/chunkers.ts

- Include source code in the bundle. This makes tracing code easier in debuggers.
- Lazily configures axios to allow axios to be tree-shook and avoid unnecessary initialization

🧹 Remove a side effect, restores missing source code

---

lib/tdf3/src/tdf.ts

This is to fix large file downloads from what I understand from @ivanovSPvirtru 😅

INT-790: Remove extra await

---

lib/package-lock.json
lib/package.json
lib/tdf3/src/models/attribute-set.ts
lib/tests/mocha/unit/attribute-set.spec.ts
remote-store/package-lock.json
web-app/package-lock.json

- We aren't doing attribute validation elsewhere
- This is less necessary after the switch to typescript
- the library is heavy and doesn't play well with our esm based tooling

chore: Removes ajv validation of attribute set

---

.github/workflows/build.yaml
.github/workflows/format.yaml
.github/workflows/large-tests.yaml
.github/workflows/publish-to.sh
.github/workflows/roundtrip/encrypt-decrypt.sh
.github/workflows/roundtrip/package-lock.json
.github/workflows/roundtrip/package.json
.github/workflows/roundtrip/wait-and-test.sh
Makefile
cli/.eslintrc.yaml
cli/README.md
cli/bin/opentdf.bats
cli/bin/opentdf.mjs
cli/package-lock.json
cli/package.json
cli/src/cli.ts
cli/src/logger.ts
cli/src/polyfills.ts
cli/tests/logger.spec.ts
cli/tsconfig.json
lib/package-lock.json
lib/tdf3/src/client/builders.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/client/validation.ts
lib/tdf3/src/models/attribute-set.ts
remote-store/package-lock.json
scripts/bump-version.sh
scripts/check-version-is.sh
web-app/package-lock.json

We [removed this CLI sample code last summer](https://github.com/opentdf/client-web/pull/207) as part of a move to go all-in on web-first code. There are still some bits of 'node-style' code around - notably we still use EventEmitter and Buffer (provided via ponyfills) - but largely have moved away from other bits of node io or networking apis. As such we have to migrate our code that previously used node's files and streams to the (newer) webstreams support.
While restoring this code, I made some changes to simplify calling the client from node:
- Simplifies ability to set attributes in TDF3Encrypt (no longer require attribute objects with KAS url)
- Removes ability to pass in an output stream to TDF3Client.encrypt
In order to work around streamsaver failing in node contexts, the cli …

feat: Adds back cli tool

---

.github/workflows/build.yaml
.github/workflows/roundtrip/config-demo-idp.sh
.github/workflows/roundtrip/docker-compose.yaml
.github/workflows/roundtrip/init-temp-keys.sh
.github/workflows/roundtrip/opentdf.yaml
.github/workflows/roundtrip/wait-and-test.sh
.gitignore
cli/package-lock.json
remote-store/package-lock.json
web-app/package-lock.json
web-app/src/config.ts
web-app/tests/tests/roundtrip.spec.ts
web-app/vite.config.ts

We have migrated to a new set of backend services and are deprecating the existing python based services. This replaces the recommended sample code with platform compatible code

chore(ci): Adds platform integration test

---

lib/src/nanotdf/models/ResourceLocator.ts

Refactor the protocol determination logic to use bitwise operations for extracting protocol index. This change simplifies the code by directly using the lower four bits of the protocol to check for HTTP or HTTPS. Additionally, enhanced the error message formatting for better readability.
Issue: https://github.com/opentdf/platform/issues/1203
Specification: https://github.com/opentdf/spec/pull/40
ADR: https://github.com/opentdf/platform/issues/900

feat(core): NanoTDF resource locator protocol bit mask

---

cli/package-lock.json
lib/package-lock.json
lib/src/nanotdf/encrypt.ts
lib/src/nanotdf/enum/ProtocolEnum.ts
lib/src/nanotdf/enum/ResourceLocatorIdentifierEnum.ts
lib/src/nanotdf/models/ResourceLocator.ts
lib/tests/web/nanotdf/ntdf-spec-basic-example.test.ts
remote-store/package-lock.json
web-app/package-lock.json

NanoTDF will now have the KAS KID set in the KAS ResourceLocator
To set the KAS KID the end-developer is must set it in `ResourceLocator.parse(kasUrl, id)` and pass it to encrypt() instead of kasUrl String
Introduces a new enum for identifier length and modifies the ResourceLocator class to include this identifier and its encoding/decoding logic. This enhances the resource locator functionality by supporting identifiers of varying lengths.
Resolves https://github.com/opentdf/client-web/issues/311
Specification: https://github.com/opentdf/spec/pull/40
ADR: https://github.com/opentdf/platform/issues/900
see also https://github.com/opentdf/client-web/pull/324

feat(core): KID in NanoTDF

---

.github/workflows/roundtrip/Tiltfile

This should fix a 404 we are getting on the integration tests

chore(ci): Update nginx ingress helm chart

---

lib/package.json
lib/src/access.ts
lib/src/nanotdf/encrypt.ts
lib/src/nanotdf/models/Header.ts
lib/src/nanotdf/models/Policy/RemotePolicy.ts
lib/src/nanotdf/models/ResourceLocator.ts
lib/tests/web/nano-roundtrip.test.ts
lib/tests/web/nanotdf/models/ResourceLocator.test.ts

- Allow kids to be any size less than 33 bytes
- refactor: replaces ResourceLocator.parse and constructor with factory methods with more sensible ones that call the same simple value-only constructor, instead of having to double-parse
- removes some stray console.logs I was using for debugging that i let get checked in
- fixes issue where sometimes queries sent to the server would have double slashes
- Adds more error checking and some tests for the error conditions (unsupported protocol and identifier type, undersized buffers)
- Deletes some duplicated methods

fix(nano): Allow padding of kids

---

lib/tdf3/src/client/validation.ts
lib/tdf3/src/tdf.ts

This PR contains changes to address regex issues discovered by CodeQL:
* https://github.com/opentdf/web-sdk/security/code-scanning/8
* https://github.com/opentdf/web-sdk/security/code-scanning/9
Changes (see also commit messages):
* First commit contains two changes.  First to ensure that `.` characters in the url and ip addresses match only the literal `.` vs interpreted as "any character".  This is both a fix to make the patterns more precise, as well as more efficent.
* The first commit also fixes the WWW_HOST TLD part of the pattern.  Specifically `^s` was switched to `a-z`.  `^s` will match any character except `s`, it is assumed that `^\s` was expected (to match any non-whitespace character).  However the `a-z` check is simpler and more precise.
* The second commit addresses …

fix: Changes to make regex patterns more efficient, accurate and simpler

---

.github/workflows/build.yaml

The 'make test' step has been removed from the GitHub Actions build workflow. This change simplifies the workflow by focusing on documentation generation and publication preparation. Any testing should be configured separately or integrated into other steps if necessary.

chore: Remove 'make test' step from deploy workflow

---

Makefile

The Makefile now ensures dependencies are installed before generating documentation. This change avoids potential issues with missing or outdated packages during the documentation process.

chore: documentation generation to include npm ci

---

lib/src/concurrency.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/concurrency.spec.ts

Lets the pool start the promises itself, instead of taking in promises that have already been scheduled on the task queue (!)

fix(sdk): Let pools take callables.

---

Makefile
cli/package-lock.json
cli/package.json
lib/package-lock.json
lib/package.json
lib/src/version.ts
lib/tdf3/src/version.ts
web-app/package-lock.json
web-app/package.json

This is because indicate that v 0.2.x and later will:
- not support v1 (entity object, etc.)
- will add a simplified and unified API for TDF manipulation, sharing patterns between different container formats
- other radical changes tbd

🆙 0.2.0 minor autobump

---

cli/package-lock.json
lib/package-lock.json
lib/package.json
lib/tdf3/src/client/DecoratedReadableStream.ts
lib/tdf3/src/tdf.ts
web-app/package-lock.json
web-app/package.json
web-app/src/App.tsx

This removes a dependency on streamsaver.js. The equivalent function to this method is now viewable in the `App.tsx` file:
```ts
async function toFile(
stream: ReadableStream<Uint8Array>,
filepath = 'download.tdf',
options?: {
encoding?: BufferEncoding;
signal?: AbortSignal;
}
): Promise<void> {
const fileStream = streamsaver.createWriteStream(filepath, {
writableStrategy: { highWaterMark: 1 },
readableStrategy: { highWaterMark: 1 },
});
return stream.pipeTo(fileStream, options);
}
```

feat!(sdk): Remove 'toFile' method

---

cli/package-lock.json
cli/package.json
cli/src/cli.ts
lib/package-lock.json
lib/package.json
lib/src/nanoclients.ts
lib/src/nanoindex.ts
lib/src/opentdf.ts
lib/src/utils.ts
lib/tdf3/index.ts
lib/tdf3/src/assertions.ts
lib/tdf3/src/client/builders.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/tdf.ts
lib/tdf3/src/utils/zip-reader.ts
lib/tests/web/nano-roundtrip.test.ts
lib/tests/web/roundtrip.test.ts
lib/tests/web/utils.test.ts
web-app/package-lock.json
web-app/package.json
web-app/src/App.tsx
web-app/tests/tests/roundtrip.spec.ts

- Creates new type `OpenTDF`, which adds 'create' and 'read' methods for TDF objects
- Sequesters old APIs into `@opentdf/sdk/singlecontainer` entry point. If the old API is desired, use this import, not `@opentdf/sdk`.

feat!(sdk): New client object api

---

cli/src/cli.ts
lib/src/opentdf.ts
lib/src/tdf/AttributeObject.ts
lib/src/tdf/Policy.ts
lib/src/tdf/PolicyObject.ts
lib/tdf3/src/models/manifest.ts
lib/tdf3/src/models/policy.ts
lib/tdf3/src/tdf.ts

- allow backward compatibility with any files that have that field set
- updates cli to infer that --kasEndpoint implies the value is allowed

fix(sdk): Sets schemaVersion, not tdf_spec_version

---

cli/src/cli.ts
lib/tdf3/src/models/key-access.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/tdf.spec.ts

- validates assertions before validating root sig (faster, errors match those expected in xtest)
- removes some unused code (remote keys)
- lets CLI tool properly return non-zero status code on more conditions

fix(cli): Better errors and properly set exit code in more cases

---

.github/workflows/build.yaml

chore(ci): Add conventional commit checks

---

.github/workflows/build.yaml

- Dependabot PRs [behave like fork PRs](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/), so they don't have access to the sonarqube secret
- Instead, skip the step where the results are pushed to sonarcloud [when appropriate](https://docs.github.com/en/code-security/dependabot/troubleshooting-dependabot/troubleshooting-dependabot-on-github-actions#troubleshooting-failures-when-dependabot-triggers-existing-workflows)

chore(ci): Don't run sonarscan for dependabot PRs

---

cli/bin/opentdf.bats
cli/src/cli.ts
lib/src/opentdf.ts

- The new API broke selecting between ECDSA and GMAC policy binding options
- This adds that feature back and fixes it in the command line tool
- Removes the incorrect ctl version number from the command line tool, as it has never returned the correct value.
- Exposes a few more missing exports that are still stuck behind the `from '@opentdf/sdk/singlecontainer'` import that integrators are actively using

fix(sdk): Lets new API set nano binding type

---

.github/workflows/build.yaml

Seems to speed up the job significantly. This run is down to 10m 32s after previously taking 18m 6s.

chore(ci): Let xtest focus on this sdk

---

lib/src/access.ts
lib/tests/server.ts

This was for debugging an old issue with v1 of the platform, and is not supported in v2

fix(sdk): Removes ntdf version header

---

.github/workflows/roundtrip/encrypt-decrypt.sh
cli/src/cli.ts
lib/package-lock.json
lib/src/opentdf.ts
lib/tdf3/src/assertions.ts
lib/tdf3/src/client/builders.ts
lib/tdf3/src/tdf.ts

**Motivation**
Hex encoding signature was removed here https://github.com/opentdf/web-sdk/pull/397 
For **decryption** `isLegacyTDF` flag was used during decryption to determine if `base64` or `base64+hex` encoding of signatures was required for the hash.
For **encryption** only `base64` was used.
Because encryption is done only with `base64` signature hashes this produces an incompatibility with legacy clients that expect the signature hash to be `base64+hex`.
Moving forward, we do not want to use `base64+hex` but we need to allow current clients to be able to encrypt files that legacy files can decrypt. This is where the motivation for this PR changes come from.
**PR Changes**
- Add `targetSpecVersion` to  `EncryptConfiguration` to force legacy encryption 
- Add `targetSpecVersion` to …

fix(sdk):  support hex encoding signature hash for legacy sdk

---

.github/workflows/build.yaml

- This should remove the prefix before the semver in the ref name

chore(ci): Fix prefix submatch operator for tags

---

.github/workflows/roundtrip/docker-compose.yaml

chainguard keycloak is now private, use the regular dockerhub keycloak

fix(ci): use keycloack docker

---

cli/src/cli.ts
lib/src/access.ts
lib/src/nanotdf/Client.ts
lib/src/opentdf.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/encrypt-decrypt.spec.ts
lib/tests/server.ts
lib/tests/web/nano-roundtrip.test.ts
lib/tests/web/nanotdf/Client.test.ts
lib/tests/web/roundtrip.test.ts

To avoid malicious KASes, when a file is decrypted we want to give the platform administrators the ability to make sure that that KAS is within the platform's allowed KASes.
For this we will use the gRPC endpoint `/policy.kasregistry.KeyAccessServerRegistryService/ListKeyAccessServers` that will return the list of allowed KAS during decryption process and verify that the requested KAS is within that list.
- adds `fetchKeyAccessServers()` function to get the allowed kas list
- adds `platformUrl` parameter to the various clients
- adds a safeguard to throw error when neither `platformUrl` nor `allowedKasList` is passed
The `platformUrl` is changing the clients API signature and is a breaking change. To minimize this breaking change here is the list of the scenarios and in which the …

feat(sdk): get KASes list from platform when allowedKases list is not passed

---

cli/package-lock.json
lib/package.json
lib/src/platform.ts
web-app/package-lock.json
web-app/src/components/ConnectRpcExample.tsx

**Motivation**
When creating RPC requests, we want to have the ability to define the `type` of the request. Connect RPC generated platform provides those types.
The issue is that typescript named exports do not export the types. Meaning this line  only ends up exporting the values from common. Not the types. 
```js
export * as common from './platform/common/common_pb.js';
```
The types are currently in the build already, just not accessible. This PR makes the types accessible
**PR changes**
Exports everything  from the generated client`/dist/lib/platform*` as `/platform/*` from the package.json. 
This allows for all the types to be accessible
Examples of how a type can be imported now 
```js
import { ActiveStateEnum } from '@opentdf/sdk/platform/common/common_pb.js';
```

feat: export connect rpc generated platform from package.json

---

cli/package-lock.json
lib/src/access.ts
lib/src/access/access-rpc.ts
lib/src/opentdf.ts
lib/tdf3/src/client/index.ts
lib/tdf3/src/tdf.ts
lib/tests/mocha/unit/tdf.spec.ts
lib/tests/server.ts
lib/tests/web/roundtrip.test.ts
web-app/package-lock.json

**Motivation**
We want to ensures the Web SDK securely and consistently uses the "Base Key" from the WellKnown endpoint for cryptographic operations, provides a fallback when other keys are missing. 
--- 
**PR Changes**
- updates fetchPublicKey to read the Public Key from BaseKey in the Wellknown Configuration  and fallback to PublicKey
- Added integration tests to cover new functionality
---
**Use BaseKey flow**
**Scenario ZTDF **
ztdf encrypt reaches out to WellKnown to get public key
- Base Key is RSA: encryption succeeds
- Base Key is ECC: encryption succeeds
- Base Key not set: encryption succeeds with PublicKey fallback
**Scenario Nano**
nano encrypt reaches out to WellKnown to get public key.
- Base Key is RSA: encryption fails
- Base Key is ECC: encryption succeeds
- Base key not …

feat(sdk): get kas public key from base key in wellknown config
