opentdf/web-sdk

cli/package-lock.json, cli/package.json, lib/package-lock.json, lib/package.json, sample-web-app/package-lock.json, sample-web-app/package.json
update package.json to BSD-3-Clause-Clear
=> BSD-3-Clause-Clear

cli/package-lock.json, cli/package.json, lib/package.json, sample-web-app/package-lock.json, sample-web-app/package.json
- CC-BY-4 is an OSI approved OSS license that meets the other criteria we have for MIT and BSD licenses.
- The only package we transitively depend on that uses it is already allowed
=> 📄 License check update

cli/package-lock.json, lib/package-lock.json, lib/package.json, sample-web-app/package-lock.json
- Faster and more compatible with newer nodejs and tsc features
=> ⬆️ Replace nyc with c8

.github/workflows/publish-to.sh
https://github.com/opentdf/client-web/runs/8229229998?check_suite_focus=true#step:5:20
=> surpress warning

.github/workflows/build.yaml, .github/workflows/publish-to.sh
=> 🐛 Fix dist-tag, missing build step

.github/workflows/roundtrip/encrypt-decrypt.sh, lib/tdf3/src/client/validation/patterns.ts, lib/tdf3/src/client/validation/validations.ts
- Fix attribute regex to match KAS attribute regex
- Update test to not continue to succeed after first test succeeds by varying the input and being a little bit better (but not great) about cleaning up after
=> 🐛 Let attributes have capital letters and dashes

.github/workflows/build.yaml
I accidentally quoted the `>>` operator
=> ✏️ Fixes accidentally quoted bash operator

.github/workflows/publish-to.sh
Should fix: https://github.com/opentdf/client-web/actions/runs/3894519601/jobs/6648693264#step:9:11
=> 🐛 Fix bad paths in publish-to script

lib/tdf3/src/tdf.ts
Can't reach 'outside' of the root directory...
=> 🐛 Fix invalid relative import

.github/workflows/build.yaml, .github/workflows/large-tests.yaml, cli/package-lock.json, web-app/package-lock.json, web-app/src/App.tsx, web-app/tests/playwright.config.ts, web-app/tests/tests/huge.spec.ts
- Improves log statements to include time estimate
- Increases playwright timeouts to 15 minutes
- Deletes temp files after tests finish
- Reduce huge test file size from 8 to 5 GiB
=> 🌲 Some improvements for huge tests

Makefile, lib/package-lock.json, lib/package.json, lib/src/package.json, lib/src/version.ts, lib/tdf3/package.json, lib/tdf3/src/version.ts, lib/tests/package.json, lib/tsconfig.commonjs.json, scripts/add-module-types.sh, web-app/package-lock.json, web-app/package.json
This may still fail downstream because two deps don't seem to support CJS
- dpop
- browser-fs-access
If this causes a problem downstream we'll have to maybe inline those with babel or something?
=> 🐛 Second attempt at adding back CommonJS Support

lib/tdf3/src/crypto/declarations.ts, lib/tdf3/src/crypto/index.ts, lib/tdf3/src/tdf.ts
I don't understand them well enough to make a good generic interface yet
=> 🏷️ Remove generic from CryptoService

.github/workflows/build.yaml, lib/package.json, sonar-project.properties
=> Add Sonar Cloud analysis with getting Code Coverage

lib/tdf3/index.ts, remote-store/package-lock.json, web-app/package-lock.json
This is used indirectly in virtru-sdk
=> ✨ Expose cipher library

lib/package-lock.json, lib/package.json, lib/tests/mocha/setup.ts, remote-store/package-lock.json, remote-store/package.json, web-app/package-lock.json
PLAT-2858
covers:
- https://github.com/opentdf/client-web/pull/253
- https://github.com/opentdf/client-web/pull/252
- https://github.com/opentdf/client-web/pull/251
=> ⬆️ axios update

lib/tdf3/src/client/DecoratedReadableStream.ts, lib/tdf3/src/client/builders.ts, remote-store/package-lock.json, remote-store/src/index.ts, web-app/package-lock.json
=> 🔥 Remove contentLength from stream wrapper

.github/workflows/build.yaml, web-app/src/session.ts
- Improve readability of multiline strings in workflow files
- Lets web app demo work with any crypto service backend. These backends may require exporting the key to use with their own crypto routines
=> chore(cleanups): Some minor cleanups

.github/workflows/format.yaml
Closes https://github.com/opentdf/client-web/issues/297
=> fix(ci): ignore auto-formatting of proto-generated files

cli/src/cli.ts
V2 Platform does not support upsert, use offline mode by default in the cli
=> Use offline mode in cli for TDF3

.github/workflows/build.yaml, lib/tdf3/src/models/key-access.ts, lib/tests/mocks/client/default_manifest.json, lib/tests/mocks/tdf/0.manifest.json
see https://github.com/opentdf/client-web/pull/309#issue-2420948767
=> Use new policy binding format

.github/workflows/build.yaml, .github/workflows/roundtrip/encrypt-decrypt.sh, cli/bin/opentdf.bats, cli/package-lock.json, cli/src/cli.ts, lib/src/access.ts, lib/src/nanotdf/Client.ts, lib/src/utils.ts, lib/tdf3/src/client/index.ts, lib/tdf3/src/tdf.ts, lib/tests/mocha/unit/tdf.spec.ts, lib/tests/web/utils.test.ts, remote-store/package-lock.json, web-app/package-lock.json
e.g.
```
opentdf.mjs --allowList https://kas.a,https://kas.b
```
=> feat(cli): Adds --allowList parameter to cli

cli/package-lock.json, cli/src/cli.ts, lib/src/index.ts, remote-store/package-lock.json, web-app/package-lock.json
Only effective with `-t nano`, this enables the ECDSA binding type to verify the policy is attached to the key is as expected.
=> feat(cli): Adds `--policyBinding ecdsa` option

README.md
- Uses newer 'options object' constructor parameter
- Be more clear about what the auth providers are and how to select one, or write your own
=> chore(docs): Improve readme samples

lib/tdf3/src/tdf.ts
fixes typo when checking response status
successful error detection in xtest https://github.com/opentdf/tests/actions/runs/11635869428/job/32406122022?pr=220
=> fix: Rewrap response handling typo

lib/src/concurrency.ts, lib/tdf3/src/client/builders.ts, lib/tdf3/src/client/index.ts, lib/tdf3/src/tdf.ts, lib/tests/mocha/unit/concurrency.spec.ts
- Adds new `concurrencyLimit` decrypt param, which sets a thread pool (kinda)
- Defaults value to 1
=> fix(sdk): Disable concurrency on rewrap

lib/src/opentdf.ts
- renames NanoHeaderCache to the more general RewrapCache
- Exposes polling interval, max age, and 'enabled' parameters via OpenTDF constructor option
=> feat(sdk): Adds opts for collection cache

.github/workflows/roundtrip/config-demo-idp.sh, .github/workflows/roundtrip/encrypt-decrypt.sh, .github/workflows/roundtrip/wait-and-test.sh
create a new client with the right audience
=> fix(ci): Get platform_roundtrip working again

.github/dependabot.yml
- lets npm update PRs follow conventional commit configuration
- Customizes github-actions updater
=> chore(ci): Adds dependabot config

Makefile, cli/package-lock.json, cli/package.json, lib/package-lock.json, lib/package.json, lib/src/version.ts, web-app/package-lock.json, web-app/package.json
- Updates target version to 0.3.0 to indicate new features, notably we are adding EC wrapped KAO support
=> feat(sdk): Bump for EC feature

cli/src/cli.ts, lib/src/access.ts, lib/src/opentdf.ts
Ensure were adding the base platform kas to the allowlist when fetching from the registry
Pass the platform url correctly in the cli
Use the platform url from opts in nano decrypt (match behavior of tdf3)
=> feat(cli): Pass the platform url on decrypt, add the platform kas to the allowlist when fetching

scripts/check-version-is.sh, scripts/deliver-to-npm-registry.sh
Include release-please annotation in grep/sed lines, as needed
=> chore(ci): version.ts check for release-please
